- id: mypy
  name: mypy
  entry: runmypy
  args: [--ignore-missing-imports, --scripts-are-modules, --non-interactive, --install-types]
  'types_or': [python, pyi]
  language: python
  additional_dependencies:
    - mypy==1.5.1
    - pipenv
  pass_filenames: false
  require_serial: true
  minimum_pre_commit_version: 2.9.2
