- id: mypy
  name: mypy
  entry: runmypy
  args: [--scripts-are-modules, --non-interactive, --install-types]
  'types_or': [python, pyi]
  language: python
  pass_filenames: true
  require_serial: true
  minimum_pre_commit_version: 2.9.2
