[project]
name = "precommit-mypy-pipenv"
requires-python = ">=3.8"
version = "0.0.0"
dependencies = [
    "mypy==1.8.0",
    "tomli; python_version < '3.11'",
    "pipenv",
]

[project.scripts]
runmypy = "hooks.runmypy:main"

[tool.setuptools]
packages = [
    "hooks",
]
