name: master
on:
  push:
    branches: [master]
  workflow_dispatch:
  schedule:
  - cron: '0 0 * * *'

jobs:
  build:
    name: master
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
    - run: python -m pip install "urllib3>=2" tomli-w tomli packaging
    - run: git config --global user.name 'Github Actions'
    - run: git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
    - run: python bump.py
    - run: |
        git remote set-url origin https://x-access-token:$GH_TOKEN@github.com/$GITHUB_REPOSITORY
        git push origin HEAD:refs/heads/master --tags
        git tag | grep -v "$(gh release ls | cut -f3)" | xargs -i gh release create {} --notes "Bump mypy: {}"
        gh release edit "$(git tag | tail -1)" --latest
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
